// Code generated by protoc-gen-go. DO NOT EDIT.
// source: minikafka.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Topic struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_minikafka_07f0578420994a20, []int{0}
}
func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (dst *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(dst, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Payload struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_minikafka_07f0578420994a20, []int{1}
}
func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (dst *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(dst, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ProduceRequest struct {
	Topic                *Topic   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload              *Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceRequest) Reset()         { *m = ProduceRequest{} }
func (m *ProduceRequest) String() string { return proto.CompactTextString(m) }
func (*ProduceRequest) ProtoMessage()    {}
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_minikafka_07f0578420994a20, []int{2}
}
func (m *ProduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceRequest.Unmarshal(m, b)
}
func (m *ProduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceRequest.Marshal(b, m, deterministic)
}
func (dst *ProduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceRequest.Merge(dst, src)
}
func (m *ProduceRequest) XXX_Size() int {
	return xxx_messageInfo_ProduceRequest.Size(m)
}
func (m *ProduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceRequest proto.InternalMessageInfo

func (m *ProduceRequest) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *ProduceRequest) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type MsgNumber struct {
	MsgNumber            uint32   `protobuf:"varint,1,opt,name=msg_number,json=msgNumber,proto3" json:"msg_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNumber) Reset()         { *m = MsgNumber{} }
func (m *MsgNumber) String() string { return proto.CompactTextString(m) }
func (*MsgNumber) ProtoMessage()    {}
func (*MsgNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_minikafka_07f0578420994a20, []int{3}
}
func (m *MsgNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNumber.Unmarshal(m, b)
}
func (m *MsgNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNumber.Marshal(b, m, deterministic)
}
func (dst *MsgNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNumber.Merge(dst, src)
}
func (m *MsgNumber) XXX_Size() int {
	return xxx_messageInfo_MsgNumber.Size(m)
}
func (m *MsgNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNumber.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNumber proto.InternalMessageInfo

func (m *MsgNumber) GetMsgNumber() uint32 {
	if m != nil {
		return m.MsgNumber
	}
	return 0
}

type PollRequest struct {
	Topic                string     `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	ReadFrom             *MsgNumber `protobuf:"bytes,2,opt,name=read_from,json=readFrom,proto3" json:"read_from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PollRequest) Reset()         { *m = PollRequest{} }
func (m *PollRequest) String() string { return proto.CompactTextString(m) }
func (*PollRequest) ProtoMessage()    {}
func (*PollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_minikafka_07f0578420994a20, []int{4}
}
func (m *PollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollRequest.Unmarshal(m, b)
}
func (m *PollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollRequest.Marshal(b, m, deterministic)
}
func (dst *PollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollRequest.Merge(dst, src)
}
func (m *PollRequest) XXX_Size() int {
	return xxx_messageInfo_PollRequest.Size(m)
}
func (m *PollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PollRequest proto.InternalMessageInfo

func (m *PollRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PollRequest) GetReadFrom() *MsgNumber {
	if m != nil {
		return m.ReadFrom
	}
	return nil
}

type PollResponse struct {
	// payloads holds the returned messages.
	Payloads []*Payload `protobuf:"bytes,1,rep,name=payloads,proto3" json:"payloads,omitempty"`
	// new_read_from tells the requester where they should update their
	// read_from value to to move past the returned messages.
	NewReadFrom          *MsgNumber `protobuf:"bytes,2,opt,name=new_read_from,json=newReadFrom,proto3" json:"new_read_from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PollResponse) Reset()         { *m = PollResponse{} }
func (m *PollResponse) String() string { return proto.CompactTextString(m) }
func (*PollResponse) ProtoMessage()    {}
func (*PollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_minikafka_07f0578420994a20, []int{5}
}
func (m *PollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollResponse.Unmarshal(m, b)
}
func (m *PollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollResponse.Marshal(b, m, deterministic)
}
func (dst *PollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollResponse.Merge(dst, src)
}
func (m *PollResponse) XXX_Size() int {
	return xxx_messageInfo_PollResponse.Size(m)
}
func (m *PollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PollResponse proto.InternalMessageInfo

func (m *PollResponse) GetPayloads() []*Payload {
	if m != nil {
		return m.Payloads
	}
	return nil
}

func (m *PollResponse) GetNewReadFrom() *MsgNumber {
	if m != nil {
		return m.NewReadFrom
	}
	return nil
}

func init() {
	proto.RegisterType((*Topic)(nil), "protocol.Topic")
	proto.RegisterType((*Payload)(nil), "protocol.Payload")
	proto.RegisterType((*ProduceRequest)(nil), "protocol.ProduceRequest")
	proto.RegisterType((*MsgNumber)(nil), "protocol.MsgNumber")
	proto.RegisterType((*PollRequest)(nil), "protocol.PollRequest")
	proto.RegisterType((*PollResponse)(nil), "protocol.PollResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MiniKafkaClient is the client API for MiniKafka service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MiniKafkaClient interface {
	// Produce returns the message number assigned to the stored message.
	Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*MsgNumber, error)
	Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error)
}

type miniKafkaClient struct {
	cc *grpc.ClientConn
}

func NewMiniKafkaClient(cc *grpc.ClientConn) MiniKafkaClient {
	return &miniKafkaClient{cc}
}

func (c *miniKafkaClient) Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*MsgNumber, error) {
	out := new(MsgNumber)
	err := c.cc.Invoke(ctx, "/protocol.MiniKafka/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniKafkaClient) Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error) {
	out := new(PollResponse)
	err := c.cc.Invoke(ctx, "/protocol.MiniKafka/Poll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiniKafkaServer is the server API for MiniKafka service.
type MiniKafkaServer interface {
	// Produce returns the message number assigned to the stored message.
	Produce(context.Context, *ProduceRequest) (*MsgNumber, error)
	Poll(context.Context, *PollRequest) (*PollResponse, error)
}

func RegisterMiniKafkaServer(s *grpc.Server, srv MiniKafkaServer) {
	s.RegisterService(&_MiniKafka_serviceDesc, srv)
}

func _MiniKafka_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniKafkaServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.MiniKafka/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniKafkaServer).Produce(ctx, req.(*ProduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniKafka_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniKafkaServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.MiniKafka/Poll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniKafkaServer).Poll(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MiniKafka_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.MiniKafka",
	HandlerType: (*MiniKafkaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _MiniKafka_Produce_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _MiniKafka_Poll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minikafka.proto",
}

func init() { proto.RegisterFile("minikafka.proto", fileDescriptor_minikafka_07f0578420994a20) }

var fileDescriptor_minikafka_07f0578420994a20 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x57, 0x75, 0x6e, 0xbd, 0xdb, 0x1c, 0x5e, 0xff, 0x50, 0x06, 0x83, 0x11, 0x11, 0x44,
	0x71, 0xc8, 0x7c, 0x18, 0xf8, 0x01, 0x7c, 0x91, 0xc9, 0x08, 0xfa, 0x3c, 0xba, 0x35, 0x1b, 0x65,
	0x4d, 0x52, 0x93, 0xd6, 0xe1, 0x9b, 0x1f, 0x5d, 0x9a, 0xa6, 0x6b, 0x95, 0x3e, 0xf8, 0xd4, 0xdc,
	0xe6, 0xe4, 0xfc, 0xee, 0xb9, 0x17, 0xfa, 0x3c, 0x14, 0xe1, 0xd6, 0x5f, 0x6f, 0xfd, 0x71, 0xac,
	0x64, 0x22, 0xb1, 0x6d, 0x3e, 0x2b, 0x19, 0x91, 0x21, 0x34, 0xdf, 0x64, 0x1c, 0xae, 0xf0, 0x1c,
	0x9a, 0x49, 0x76, 0xf0, 0x9c, 0x91, 0x73, 0xe3, 0xd2, 0xbc, 0x20, 0x57, 0xd0, 0x9a, 0xfb, 0x5f,
	0x91, 0xf4, 0x03, 0xf4, 0xa0, 0x15, 0xe7, 0x47, 0x23, 0xe9, 0xd2, 0xa2, 0x24, 0x01, 0x9c, 0xcc,
	0x95, 0x0c, 0xd2, 0x15, 0xa3, 0xec, 0x23, 0x65, 0x3a, 0xc1, 0xeb, 0xaa, 0x59, 0x67, 0xd2, 0x1f,
	0x17, 0xbc, 0xb1, 0x81, 0x59, 0x77, 0xbc, 0x2b, 0x2d, 0x0f, 0x8c, 0xf0, 0xb4, 0x14, 0x5a, 0x6c,
	0x49, 0xb9, 0x05, 0x77, 0xa6, 0x37, 0xaf, 0x29, 0x5f, 0x32, 0x85, 0x43, 0x00, 0xae, 0x37, 0x0b,
	0x61, 0x2a, 0x43, 0xe9, 0x51, 0x97, 0x17, 0xd7, 0xe4, 0x1d, 0x3a, 0x73, 0x19, 0x45, 0x45, 0x3b,
	0xb5, 0xd9, 0xf0, 0x01, 0x5c, 0xc5, 0xfc, 0x60, 0xb1, 0x56, 0x92, 0x5b, 0xfe, 0x59, 0xc9, 0xdf,
	0xb3, 0x68, 0x3b, 0x53, 0x3d, 0x2b, 0xc9, 0xc9, 0x27, 0x74, 0x73, 0x5b, 0x1d, 0x4b, 0xa1, 0x19,
	0xde, 0x43, 0xdb, 0x76, 0xa7, 0x3d, 0x67, 0x74, 0x58, 0x1f, 0x60, 0x2f, 0xc1, 0x29, 0xf4, 0x04,
	0xdb, 0x2d, 0xfe, 0x05, 0xed, 0x08, 0xb6, 0xa3, 0x96, 0x3b, 0xf9, 0x76, 0xc0, 0x9d, 0x85, 0x22,
	0x7c, 0xc9, 0x56, 0x88, 0x4f, 0xd0, 0xb2, 0xe3, 0x46, 0xaf, 0x82, 0xfb, 0xb5, 0x81, 0x41, 0x9d,
	0x29, 0x69, 0xe0, 0x14, 0x8e, 0xb2, 0x04, 0x78, 0x51, 0x79, 0x58, 0x0e, 0x6a, 0x70, 0xf9, 0xf7,
	0x77, 0x1e, 0x94, 0x34, 0x96, 0xc7, 0xe6, 0xe2, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x77,
	0xfc, 0x23, 0x4b, 0x02, 0x00, 0x00,
}
