// Code generated by protoc-gen-go. DO NOT EDIT.
// source: toykafka.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Topic struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_toykafka_21a3ffd99066f8b6, []int{0}
}
func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (dst *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(dst, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Payload struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_toykafka_21a3ffd99066f8b6, []int{1}
}
func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (dst *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(dst, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ProduceRequest struct {
	Topic                *Topic   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload              *Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceRequest) Reset()         { *m = ProduceRequest{} }
func (m *ProduceRequest) String() string { return proto.CompactTextString(m) }
func (*ProduceRequest) ProtoMessage()    {}
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_toykafka_21a3ffd99066f8b6, []int{2}
}
func (m *ProduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceRequest.Unmarshal(m, b)
}
func (m *ProduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceRequest.Marshal(b, m, deterministic)
}
func (dst *ProduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceRequest.Merge(dst, src)
}
func (m *ProduceRequest) XXX_Size() int {
	return xxx_messageInfo_ProduceRequest.Size(m)
}
func (m *ProduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceRequest proto.InternalMessageInfo

func (m *ProduceRequest) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *ProduceRequest) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type MsgNumber struct {
	MsgNumber            int32    `protobuf:"varint,1,opt,name=msg_number,json=msgNumber,proto3" json:"msg_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNumber) Reset()         { *m = MsgNumber{} }
func (m *MsgNumber) String() string { return proto.CompactTextString(m) }
func (*MsgNumber) ProtoMessage()    {}
func (*MsgNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_toykafka_21a3ffd99066f8b6, []int{3}
}
func (m *MsgNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNumber.Unmarshal(m, b)
}
func (m *MsgNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNumber.Marshal(b, m, deterministic)
}
func (dst *MsgNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNumber.Merge(dst, src)
}
func (m *MsgNumber) XXX_Size() int {
	return xxx_messageInfo_MsgNumber.Size(m)
}
func (m *MsgNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNumber.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNumber proto.InternalMessageInfo

func (m *MsgNumber) GetMsgNumber() int32 {
	if m != nil {
		return m.MsgNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*Topic)(nil), "protocol.Topic")
	proto.RegisterType((*Payload)(nil), "protocol.Payload")
	proto.RegisterType((*ProduceRequest)(nil), "protocol.ProduceRequest")
	proto.RegisterType((*MsgNumber)(nil), "protocol.MsgNumber")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToyKafkaClient is the client API for ToyKafka service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToyKafkaClient interface {
	Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*MsgNumber, error)
}

type toyKafkaClient struct {
	cc *grpc.ClientConn
}

func NewToyKafkaClient(cc *grpc.ClientConn) ToyKafkaClient {
	return &toyKafkaClient{cc}
}

func (c *toyKafkaClient) Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*MsgNumber, error) {
	out := new(MsgNumber)
	err := c.cc.Invoke(ctx, "/protocol.ToyKafka/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToyKafkaServer is the server API for ToyKafka service.
type ToyKafkaServer interface {
	Produce(context.Context, *ProduceRequest) (*MsgNumber, error)
}

func RegisterToyKafkaServer(s *grpc.Server, srv ToyKafkaServer) {
	s.RegisterService(&_ToyKafka_serviceDesc, srv)
}

func _ToyKafka_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToyKafkaServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ToyKafka/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToyKafkaServer).Produce(ctx, req.(*ProduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToyKafka_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ToyKafka",
	HandlerType: (*ToyKafkaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _ToyKafka_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "toykafka.proto",
}

func init() { proto.RegisterFile("toykafka.proto", fileDescriptor_toykafka_21a3ffd99066f8b6) }

var fileDescriptor_toykafka_21a3ffd99066f8b6 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc9, 0xaf, 0xcc,
	0x4e, 0x4c, 0xcb, 0x4e, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9,
	0x39, 0x4a, 0xb2, 0x5c, 0xac, 0x21, 0xf9, 0x05, 0x99, 0xc9, 0x42, 0x22, 0x5c, 0xac, 0x25, 0x20,
	0x86, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0xa3, 0xa4, 0xcc, 0xc5, 0x1e, 0x90, 0x58,
	0x99, 0x93, 0x9f, 0x98, 0x22, 0x24, 0xc1, 0xc5, 0x5e, 0x00, 0x61, 0x82, 0x95, 0xf0, 0x04, 0xc1,
	0xb8, 0x4a, 0x29, 0x5c, 0x7c, 0x01, 0x45, 0xf9, 0x29, 0xa5, 0xc9, 0xa9, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x42, 0xaa, 0xc8, 0x86, 0x71, 0x1b, 0xf1, 0xeb, 0xc1, 0xec, 0xd3, 0x03, 0x5b,
	0x06, 0x35, 0x5d, 0x48, 0x1b, 0x61, 0x24, 0x13, 0x58, 0xa1, 0x20, 0x42, 0x21, 0xd4, 0x5a, 0x84,
	0x2d, 0x5a, 0x5c, 0x9c, 0xbe, 0xc5, 0xe9, 0x7e, 0xa5, 0xb9, 0x49, 0xa9, 0x45, 0x42, 0xb2, 0x5c,
	0x5c, 0xb9, 0xc5, 0xe9, 0xf1, 0x79, 0x60, 0x1e, 0xd8, 0x16, 0xd6, 0x20, 0xce, 0x5c, 0x98, 0xb4,
	0x91, 0x1b, 0x17, 0x47, 0x48, 0x7e, 0xa5, 0x37, 0xc8, 0xc7, 0x42, 0x56, 0x5c, 0xec, 0x50, 0xd7,
	0x09, 0x49, 0x20, 0x19, 0x8f, 0xe2, 0x60, 0x29, 0x61, 0x84, 0x0c, 0xdc, 0x12, 0x25, 0x86, 0x24,
	0x36, 0xb0, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xcf, 0xfe, 0x76, 0x40, 0x01, 0x00,
	0x00,
}
